<?php
require __DIR__ . '/config.php';
// Note: $isAdviser below means "this page instance manages advisers" (i.e.
// admin_advisers.php), not "the logged-in user is an adviser" -- the two
// are unrelated and it's easy to conflate them when editing this file.
$managementType = ($managementType ?? '') === 'adviser' ? 'adviser' : 'student';
$isAdviser = $managementType === 'adviser';
$archiveWorkspace = $archiveWorkspace ?? false;
// Hierarchical user management (feature request 4): a research adviser can
// manage their OWN students here, but only RPMS admin manages the adviser
// roster itself.
$authUser = require_login(($archiveWorkspace || $isAdviser) ? 'admin' : ['admin', 'adviser']);
require_once __DIR__ . '/includes/academic_catalog.php';
$user_name = $authUser['full_name']; $user_email = $authUser['email'];
$user_role = $_SESSION['user_role'] ?? 'RPMS Administrator'; $profile_img = 'assets/images/default-avatar.svg';
$loggedInRole = $_SESSION['account_type'] ?? 'admin';
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo $archiveWorkspace?'Archived Accounts':($isAdviser?'Research Advisers':'Student Records'); ?> | PRISM</title><script>try{if(localStorage.getItem('prismTheme')==='dark')document.documentElement.classList.add('dark-theme')}catch(_){}</script><link rel="icon" href="assets/images/prismicon.png"><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/dashboard.css'), ENT_QUOTES, 'UTF-8'); ?>"><link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/admin-management.css'), ENT_QUOTES, 'UTF-8'); ?>"><link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/prism-ui.css'), ENT_QUOTES, 'UTF-8'); ?>"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"><link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/dashboard-sidebar.css'), ENT_QUOTES, 'UTF-8'); ?>">
<script src="<?php echo htmlspecialchars(asset_url('assets/js/dashboard-sidebar.js'), ENT_QUOTES, 'UTF-8'); ?>" defer></script>
<?php if (!$isAdviser): ?><link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/academic-fields.css'), ENT_QUOTES, 'UTF-8'); ?>"><?php endif; ?>
<link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/ceu-footer.css'), ENT_QUOTES, 'UTF-8'); ?>">
<link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/prism-workspace.css'), ENT_QUOTES, 'UTF-8'); ?>">
<script src="<?php echo htmlspecialchars(asset_url('assets/js/prism-workspace.js'), ENT_QUOTES, 'UTF-8'); ?>" defer></script>
</head>
<body class="prism-workspace <?= $authUser['role'] === 'admin' ? 'admin-shell' : 'portal-shell adviser-page' ?>" data-admin-user="<?php echo htmlspecialchars(hash('sha256',$user_email),ENT_QUOTES); ?>" data-management="<?php echo $managementType; ?>" data-archive-workspace="<?= $archiveWorkspace ? 'true' : 'false' ?>" data-user-role="<?php echo htmlspecialchars($loggedInRole, ENT_QUOTES, 'UTF-8'); ?>"><script>window.PRISM_STAGE_LABELS = <?php echo json_encode(stage_labels_map(), JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?>;</script><div class="container"><?php if ($authUser['role'] === 'admin'): ?><aside class="sidebar prism-sidebar"><?php else: ?><header class="portal-navbar"><?php endif; ?>
<?php $prismCurrentPage = $archiveWorkspace ? 'admin_archived_accounts.php' : ($isAdviser ? 'admin_advisers.php' : 'admin_students.php'); require __DIR__ . '/includes/prism-navigation.php'; ?>
<?php if ($authUser['role'] === 'admin'): ?></aside><?php else: ?></header><?php endif; ?>
<main class="main-content management-page"><header class="topbar"><div><h1><?php echo $archiveWorkspace?'Archived Accounts':($isAdviser?'Research Advisers':'Student Records'); ?></h1><p><?php echo $archiveWorkspace?'Review archived accounts, restore access, and manage existing retention controls.':($isAdviser?'Manage research adviser accounts and research-group assignments.':($loggedInRole === 'adviser' ? 'Manage your own assigned students.' : 'Manage records, research groups, and adviser assignments.')); ?></p></div><div class="top-controls"><button type="button" class="theme-toggle" id="themeToggle" title="Toggle light or dark theme" aria-label="Toggle light or dark theme"><i class="fa-solid fa-sun light-icon" aria-hidden="true"></i><i class="fa-solid fa-moon dark-icon" aria-hidden="true"></i></button></div></header><section class="management-controls"><div class="management-search"><i class="fa-solid fa-magnifying-glass"></i><input id="recordSearch" placeholder="Search records"></div><?php if (!$archiveWorkspace): ?><button type="button" class="management-primary" id="inviteAccount">Invite <?php echo $isAdviser?'Adviser':'Student'; ?></button><button class="management-primary" id="addRecord"><i class="fa-solid fa-plus"></i> Add <?php echo $isAdviser?'Research Adviser':'Student'; ?></button><?php endif; ?><?php if ($loggedInRole === 'admin'): ?><a class="prism-btn prism-btn-secondary" href="<?= $archiveWorkspace ? ($isAdviser ? 'admin_advisers.php' : 'admin_students.php') : ('admin_archived_accounts.php?type=' . $managementType) ?>"><?= $archiveWorkspace ? 'View Current Records' : 'View Archived Accounts' ?></a><?php endif; ?></section><?php if ($archiveWorkspace): ?><nav class="archive-tabs" aria-label="Archived account type"><a class="prism-btn prism-btn-secondary" href="admin_archived_accounts.php?type=student" <?= !$isAdviser ? 'aria-current="page"' : '' ?>>Students</a><a class="prism-btn prism-btn-secondary" href="admin_archived_accounts.php?type=adviser" <?= $isAdviser ? 'aria-current="page"' : '' ?>>Research Advisers</a></nav><?php endif; ?><?php if ($archiveWorkspace): ?><p id="permanentDeleteAvailability" role="status" aria-live="polite">Checking permanent-delete schema verification...</p><?php endif; ?>
<div id="recordFilters" class="prism-record-filters" aria-label="Record filters and sorting"></div><section class="management-card"><div class="management-card-head"><div><h2><?php echo $archiveWorkspace?($isAdviser?'Archived Research Advisers':'Archived Students'):($isAdviser?'Research Adviser Accounts':'Student Records'); ?></h2><p id="recordCount">0 records</p></div></div><div class="management-table-wrap"><table><thead><tr><?php if($archiveWorkspace): ?><th>Name / Email</th><th><?= $isAdviser ? 'Employee ID' : 'Student ID' ?></th><th>Academic Information</th><th>Research Group / Adviser</th><th>Archived Date</th><th>Retention / Delete Status</th><?php elseif($isAdviser): ?><th>Research Adviser</th><th>Employee ID</th><th>Department</th><th>Assigned Groups</th><th>Account</th><?php else: ?><th>Student</th><th>Student ID</th><th>Research / Group</th><th>Assigned Adviser</th><th>IERB Status</th><th>Protocol / PI</th><?php endif; ?><th>Actions</th></tr></thead><tbody id="recordRows"></tbody></table></div></section><?php require __DIR__ . '/includes/ceu_footer.php'; ?>

</main></div>
<?php if ($loggedInRole === 'admin'): ?>
<dialog id="permanentDeleteDialog" class="prism-dialog lifecycle-dialog" aria-labelledby="permanentDeleteTitle">
<form id="permanentDeleteForm" class="account-form lifecycle-form">
<h2 id="permanentDeleteTitle">Permanently delete account</h2>
<p id="permanentDeleteWarning">This permanently removes the account and applicable PRISM records. This action cannot be undone.</p>
<p id="permanentDeleteIdentity"></p>
<div class="lifecycle-form-group"><label for="permanentDeletePassword">Admin current password</label>
<div class="lifecycle-password"><input id="permanentDeletePassword" name="currentPassword" type="password" autocomplete="current-password" maxlength="200" required>
<button type="button" class="toggle-password lifecycle-password-toggle" data-lifecycle-password aria-label="Show password" aria-controls="permanentDeletePassword" aria-pressed="false"><i id="permanentDeletePasswordEye" class="fa-solid fa-eye" aria-hidden="true"></i></button></div></div>
<div class="lifecycle-form-group"><label id="permanentDeleteConfirmationLabel" for="permanentDeleteConfirmation">Type the exact account ID</label><input id="permanentDeleteConfirmation" name="confirmation" autocomplete="off" maxlength="190" required></div>
<div id="permanentDeleteReasonGroup" class="lifecycle-form-group" hidden><label for="permanentDeleteReason">Reason (do not include personal or document details)</label><textarea id="permanentDeleteReason" name="reason" minlength="5" maxlength="500" rows="3"></textarea></div>
<label class="lifecycle-check"><input name="confirmed" type="checkbox" required> I understand that permanent deletion cannot be undone.</label>
<p id="permanentDeleteResult" role="status" aria-live="polite"></p>
<div class="management-actions"><button id="cancelPermanentDelete" type="button">Cancel</button><button type="submit" class="lifecycle-danger">Permanently delete</button></div>
</form></dialog>
<script src="<?php echo htmlspecialchars(asset_url('assets/js/script.js'), ENT_QUOTES, 'UTF-8'); ?>"></script>
<script src="<?php echo htmlspecialchars(asset_url('assets/js/lifecycle-forms.js'), ENT_QUOTES, 'UTF-8'); ?>"></script>
<?php endif; ?>
<script>window.PRISM_INVITATION_DOMAINS = <?php echo json_encode(onboarding_invitation_domains(), JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?>;</script>
<dialog id="inviteDialog" class="prism-dialog lifecycle-dialog" aria-labelledby="inviteTitle"><form id="inviteForm" class="account-form lifecycle-form"><h2 id="inviteTitle">Invite account</h2><p>The invited person establishes a password and completes their own profile.</p><label for="inviteEmail">Institutional email (required)</label><input id="inviteEmail" type="email" autocomplete="email" maxlength="190" required aria-describedby="inviteDomainHint inviteEmailError">
<small id="inviteDomainHint">Allowed domains: <?php echo htmlspecialchars(implode(', ', array_map(fn($domain) => '@' . $domain, onboarding_invitation_domains())), ENT_QUOTES, 'UTF-8'); ?></small>
<p id="inviteEmailError" class="prism-field-error" aria-live="polite"></p>
<?php if(!$isAdviser && $loggedInRole==='admin'): ?><label for="inviteAdviser">Adviser (optional)</label><select id="inviteAdviser"><option value="">Unassigned</option></select><?php endif; ?>
<p id="inviteResult" role="alert" aria-live="polite" tabindex="-1"></p><div class="management-actions"><button id="cancelInvite" type="button">Cancel</button><button type="submit" class="management-primary">Send invitation</button></div></form></dialog>
<script src="<?php echo htmlspecialchars(asset_url('assets/js/invitations.js'), ENT_QUOTES, 'UTF-8'); ?>"></script>
<div class="management-modal" id="recordModal"><div class="management-dialog" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><div class="management-modal-head"><div><span>Account record</span><h2 id="modalTitle">Add Record</h2></div><button type="button" id="closeRecord" aria-label="Close record form"><i class="fa-solid fa-xmark"></i></button></div><form id="recordForm"><input type="hidden" id="recordId"><div class="management-form-grid"><label>Full name<input id="recordName" required maxlength="120"></label><label><?php echo $isAdviser?'Employee':'Student'; ?> ID<input id="accountId" required maxlength="40"></label><label>Email<input id="recordEmail" type="email" required maxlength="150"></label><?php if($isAdviser): ?><label>Academic Unit / Department<select id="department" required><option value="">Choose an academic unit</option><?php foreach (academic_catalog()['units'] as $unit): ?><option value="<?php echo htmlspecialchars($unit['label'], ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars($unit['label'], ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label><label>Account status (use Archive / Restore to change existing accounts)<select id="accountStatus"><option>Active</option><option>Inactive</option></select></label><?php else: ?><label class="wide">Research title<input id="research" maxlength="250"></label><fieldset class="academic-fields" id="studentAcademicFields"><legend>Academic information</legend><div class="academic-fields-grid">
<label for="academicUnit">Academic Unit<select id="academicUnit" data-academic="unit"></select></label>
<label for="course">Program<select id="course" data-academic="program" aria-describedby="academicSummary"></select></label>
<label for="yearLevel">Year Level<select id="yearLevel" data-academic="year"></select></label>
<label for="academicYear">Academic Year<select id="academicYear" data-academic="academic-year"></select></label>
</div><p id="academicSummary" data-academic="summary" aria-live="polite"></p><p data-academic="legacy" hidden></p><button type="button" data-academic="reset" hidden>Keep existing academic values</button></fieldset><label>Research group<select id="group" data-research-group><option value="">Select academic information first</option></select></label><label class="wide">Pending requirements<input id="requirements" maxlength="255" placeholder="Leave blank if none"></label><label id="adviserFieldLabel">Assigned research adviser<select id="adviser"><option value="">Unassigned</option></select></label><label>IERB stage<select id="stage"><option value="Stage 1">Stage 1</option><option value="Stage 2">Stage 2</option><option value="Stage 3">Stage 3</option><option value="Stage 4">Stage 4</option><option value="Stage 5">Stage 5</option><option value="Completed">Completed</option></select></label><label>Status<select id="recordStatus"><option>On Track</option><option>Pending</option><option>Delayed</option></select></label><label id="protocolCodeField" class="wide">Protocol Code<input id="protocolCode" maxlength="100" placeholder="Assigned once IERB approval is finalized"></label><label id="principalField" class="check-label">Principal Investigator<input id="isPrincipal" type="checkbox"></label><?php endif; ?></div><div class="management-actions"><button type="button" id="cancelRecord">Cancel</button><button class="management-primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Save record</button></div></form></div></div><script src="<?php echo htmlspecialchars(asset_url('assets/js/prism-ui.js'), ENT_QUOTES, 'UTF-8'); ?>"></script><?php if (!$isAdviser): ?><script>window.PRISM_ACADEMIC_CATALOG = <?php echo json_encode(academic_catalog(), JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?>;</script><script src="<?php echo htmlspecialchars(asset_url('assets/js/academic-fields.js'), ENT_QUOTES, 'UTF-8'); ?>"></script><?php endif; ?><script src="<?php echo htmlspecialchars(asset_url('assets/js/admin-retention.js'), ENT_QUOTES, 'UTF-8'); ?>"></script><script src="<?php echo htmlspecialchars(asset_url('assets/js/admin-management.js'), ENT_QUOTES, 'UTF-8'); ?>"></script></body></html>
