<?php
require __DIR__ . '/config.php';
// Note: $isAdviser below means "this page instance manages advisers" (i.e.
// admin_advisers.php), not "the logged-in user is an adviser" -- the two
// are unrelated and it's easy to conflate them when editing this file.
$managementType = ($managementType ?? '') === 'adviser' ? 'adviser' : 'student';
$isAdviser = $managementType === 'adviser';
// Hierarchical user management (feature request 4): a research adviser can
// manage their OWN students here, but only RPMS admin manages the adviser
// roster itself.
$authUser = require_login($isAdviser ? 'admin' : ['admin', 'adviser']);
if (!$isAdviser) { require_once __DIR__ . '/includes/academic_catalog.php'; }
$user_name = $authUser['full_name']; $user_email = $authUser['email'];
$user_role = $_SESSION['user_role'] ?? 'RPMS Administrator'; $profile_img = 'assets/images/default-avatar.svg';
$loggedInRole = $_SESSION['account_type'] ?? 'admin';
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo $isAdviser?'Research Adviser':'Student'; ?> Management | PRISM</title><script>try{if(localStorage.getItem('prismTheme')==='dark')document.documentElement.classList.add('dark-theme')}catch(_){}</script><link rel="icon" href="assets/images/prismicon.png"><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/dashboard.css"><link rel="stylesheet" href="assets/css/admin-management.css"><link rel="stylesheet" href="assets/css/prism-ui.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"><link rel="stylesheet" href="assets/css/dashboard-sidebar.css">
<script src="assets/js/dashboard-sidebar.js" defer></script>
<?php if (!$isAdviser): ?><link rel="stylesheet" href="assets/css/academic-fields.css"><?php endif; ?>
</head>
<body data-admin-user="<?php echo htmlspecialchars(hash('sha256',$user_email),ENT_QUOTES); ?>" data-management="<?php echo $managementType; ?>" data-user-role="<?php echo htmlspecialchars($loggedInRole, ENT_QUOTES, 'UTF-8'); ?>"><script>window.PRISM_STAGE_LABELS = <?php echo json_encode(stage_labels_map(), JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?>;</script><div class="container"><aside class="sidebar prism-sidebar">
<?php $prismCurrentPage = $isAdviser ? 'admin_advisers.php' : 'admin_students.php'; require __DIR__ . '/includes/prism-navigation.php'; ?>
<div class="sidebar-bottom"><div class="sidebar-profile"><img src="<?php echo $profile_img; ?>" alt=""><div class="profile-info"><h4><?php echo htmlspecialchars($user_name); ?></h4><p><?php echo htmlspecialchars($user_role); ?></p></div></div></div></aside>
<main class="main-content management-page"><header class="topbar"><div><h1><?php echo $isAdviser?'Research Adviser':'Student'; ?> Management</h1><p><?php echo $isAdviser?'Manage research adviser accounts and research-group assignments.':($loggedInRole === 'adviser' ? 'Manage your own assigned students.' : 'Manage records, research groups, and adviser assignments.'); ?></p></div><div class="theme-toggle" id="themeToggle"><i class="fa-solid fa-sun light-icon"></i><i class="fa-solid fa-moon dark-icon"></i></div></header><section class="management-controls"><div class="management-search"><i class="fa-solid fa-magnifying-glass"></i><input id="recordSearch" placeholder="Search records"></div><button class="management-primary" id="addRecord"><i class="fa-solid fa-plus"></i> Add <?php echo $isAdviser?'Research Adviser':'Student'; ?></button></section><section class="management-card"><div class="management-card-head"><div><h2><?php echo $isAdviser?'Research Adviser Accounts':'Student Records'; ?></h2><p id="recordCount">0 records</p></div></div><div class="management-table-wrap"><table><thead><tr><?php if($isAdviser): ?><th>Research Adviser</th><th>Employee ID</th><th>Department</th><th>Assigned Groups</th><th>Account</th><?php else: ?><th>Student</th><th>Student ID</th><th>Research / Group</th><th>Assigned Adviser</th><th>IERB Status</th><th>Protocol / PI</th><?php endif; ?><th>Actions</th></tr></thead><tbody id="recordRows"></tbody></table></div></section></main></div>
<div class="management-modal" id="recordModal"><div class="management-dialog" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><div class="management-modal-head"><div><span>Account record</span><h2 id="modalTitle">Add Record</h2></div><button type="button" id="closeRecord" aria-label="Close record form"><i class="fa-solid fa-xmark"></i></button></div><form id="recordForm"><input type="hidden" id="recordId"><div class="management-form-grid"><label>Full name<input id="recordName" required maxlength="120"></label><label><?php echo $isAdviser?'Employee':'Student'; ?> ID<input id="accountId" required maxlength="40"></label><label>Email<input id="recordEmail" type="email" required maxlength="150"></label><?php if($isAdviser): ?><label>Department<input id="department" required maxlength="100"></label><label class="wide">Assigned research groups<input id="groups" maxlength="250" placeholder="GRP-001, GRP-002"></label><label>Account status<select id="accountStatus"><option>Active</option><option>Inactive</option></select></label><?php else: ?><label class="wide">Research title<input id="research" maxlength="250"></label><fieldset class="academic-fields" id="studentAcademicFields"><legend>Academic information</legend><div class="academic-fields-grid">
<label for="academicUnit">Academic Unit<select id="academicUnit" data-academic="unit"></select></label>
<label for="course">Program<select id="course" data-academic="program" aria-describedby="academicSummary"></select></label>
<label for="yearLevel">Year Level<select id="yearLevel" data-academic="year"></select></label>
<label for="academicYear">Academic Year<select id="academicYear" data-academic="academic-year"></select></label>
</div><p id="academicSummary" data-academic="summary" aria-live="polite"></p><p data-academic="legacy" hidden></p><button type="button" data-academic="reset" hidden>Keep existing academic values</button></fieldset><label>Research group<select id="group" data-research-group><option value="">Select academic information first</option></select></label><label class="wide">Pending requirements<input id="requirements" maxlength="255" placeholder="Leave blank if none"></label><label id="adviserFieldLabel">Assigned research adviser<select id="adviser"><option value="">Unassigned</option></select></label><label>IERB stage<select id="stage"><option value="Stage 1">Stage 1</option><option value="Stage 2">Stage 2</option><option value="Stage 3">Stage 3</option><option value="Stage 4">Stage 4</option><option value="Stage 5">Stage 5</option><option value="Completed">Completed</option></select></label><label>Status<select id="recordStatus"><option>On Track</option><option>Pending</option><option>Delayed</option></select></label><label id="protocolCodeField" class="wide">Protocol Code<input id="protocolCode" maxlength="100" placeholder="Assigned once IERB approval is finalized"></label><label id="principalField" class="check-label">Principal Investigator<input id="isPrincipal" type="checkbox"></label><?php endif; ?></div><div class="management-actions"><button type="button" id="cancelRecord">Cancel</button><button class="management-primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Save record</button></div></form></div></div><script src="assets/js/prism-ui.js"></script><?php if (!$isAdviser): ?><script>window.PRISM_ACADEMIC_CATALOG = <?php echo json_encode(academic_catalog(), JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?>;</script><script src="assets/js/academic-fields.js"></script><?php endif; ?><script src="assets/js/admin-management.js"></script></body></html>
