<?php require __DIR__ . '/config.php'; $authUser = require_login('admin'); $user_name=$authUser['full_name'];$user_email=$authUser['email'];$user_role=$_SESSION['user_role']??'RPMS Administrator';$profile_img='assets/images/default-avatar.svg';?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Generated Reports | PRISM</title><script>try{if(localStorage.getItem('prismTheme')==='dark')document.documentElement.classList.add('dark-theme')}catch(_){}</script><link rel="icon" type="image/png" href="assets/images/prismicon.png"><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/dashboard.css'), ENT_QUOTES, 'UTF-8'); ?>"><link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/reports.css'), ENT_QUOTES, 'UTF-8'); ?>"><link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/prism-ui.css'), ENT_QUOTES, 'UTF-8'); ?>"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"><link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/dashboard-sidebar.css'), ENT_QUOTES, 'UTF-8'); ?>">
<script src="<?php echo htmlspecialchars(asset_url('assets/js/dashboard-sidebar.js'), ENT_QUOTES, 'UTF-8'); ?>" defer></script>
<link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/ceu-footer.css'), ENT_QUOTES, 'UTF-8'); ?>">
<link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/prism-workspace.css'), ENT_QUOTES, 'UTF-8'); ?>">
<script src="<?php echo htmlspecialchars(asset_url('assets/js/prism-workspace.js'), ENT_QUOTES, 'UTF-8'); ?>" defer></script>
</head>
<body class="prism-workspace <?= $authUser['role'] === 'admin' ? 'admin-shell' : 'portal-shell adviser-page' ?>" data-report-user="<?php echo htmlspecialchars(hash('sha256',$user_email),ENT_QUOTES,'UTF-8'); ?>" data-user-role="<?php echo htmlspecialchars($authUser['role'],ENT_QUOTES,'UTF-8'); ?>"><div class="container"><?php if ($authUser['role'] === 'admin'): ?><aside class="sidebar prism-sidebar"><?php else: ?><header class="portal-navbar"><?php endif; ?>
<?php $prismCurrentPage = 'reports.php'; require __DIR__ . '/includes/prism-navigation.php'; ?>
<?php if ($authUser['role'] === 'admin'): ?></aside><?php else: ?></header><?php endif; ?>
<main class="main-content reports-page"><header class="topbar"><div class="reports-heading"><h1>Generated Reports</h1></div><div class="top-controls"><button type="button" class="theme-toggle" id="themeToggle" title="Toggle light or dark theme" aria-label="Toggle light or dark theme"><i class="fa-solid fa-sun light-icon" aria-hidden="true"></i><i class="fa-solid fa-moon dark-icon" aria-hidden="true"></i></button></div></header>
<section class="report-tools"><a class="report-tool" href="admin_ai.php"><span class="report-tool-icon"><i class="fa-solid fa-chart-line" aria-hidden="true"></i></span><span><strong>AI Progress Reports</strong><small>Create summarized or full AI reports</small></span><i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a><button class="report-tool" id="openStudentReport"><span class="report-tool-icon"><i class="fa-solid fa-user-graduate"></i></span><span><strong>Generate Student Report</strong><small>Individual IERB progress summary</small></span><i class="fa-solid fa-chevron-right"></i></button></section>
<section class="report-history"><div class="report-history-heading"><div><h2>Report History</h2><p id="reportCount">0 reports</p></div><button id="exportExcel" class="prism-btn is-secondary"><i class="fa-solid fa-file-excel"></i> Export Excel CSV</button></div><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Report Name</th><th>Date Generated</th><th>Type</th><th>Actions</th></tr></thead><tbody id="reportTableBody"></tbody></table></div></section><?php require __DIR__ . '/includes/ceu_footer.php'; ?>
</main></div>
<div class="report-modal" id="studentModal"><div class="report-modal-dialog"><div class="report-modal-heading"><div><span>Individual report</span><h2>Student Progress Report</h2></div><button type="button" data-close="studentModal" aria-label="Close student report form"><i class="fa-solid fa-xmark"></i></button></div><form id="studentReportForm"><label>Select active student</label><select id="reportStudent" required></select><button class="generate-report-button"><i class="fa-solid fa-file-pdf"></i> Generate PDF</button></form></div></div>

<script src="<?php echo htmlspecialchars(asset_url('assets/js/prism-ui.js'), ENT_QUOTES, 'UTF-8'); ?>"></script><script src="<?php echo htmlspecialchars(asset_url('assets/js/reports.js'), ENT_QUOTES, 'UTF-8'); ?>"></script></body></html>
