<?php require __DIR__ . '/config.php'; $authUser = require_login('admin'); $user_name=$authUser['full_name'];$user_email=$authUser['email'];$user_role=$_SESSION['user_role']??'RPMS Administrator';$profile_img='assets/images/default-avatar.svg';?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Reports | CEU RPMS Workload Assistant</title><script>try{if(localStorage.getItem('prismTheme')==='dark')document.documentElement.classList.add('dark-theme')}catch(_){}</script><link rel="icon" type="image/png" href="assets/images/prismicon.png"><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/dashboard.css'), ENT_QUOTES, 'UTF-8'); ?>"><link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/reports.css'), ENT_QUOTES, 'UTF-8'); ?>"><link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/prism-ui.css'), ENT_QUOTES, 'UTF-8'); ?>"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"><link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/dashboard-sidebar.css'), ENT_QUOTES, 'UTF-8'); ?>">
<script src="<?php echo htmlspecialchars(asset_url('assets/js/dashboard-sidebar.js'), ENT_QUOTES, 'UTF-8'); ?>" defer></script>
<link rel="stylesheet" href="<?php echo htmlspecialchars(asset_url('assets/css/ceu-footer.css'), ENT_QUOTES, 'UTF-8'); ?>">
</head>
<body data-report-user="<?php echo htmlspecialchars(hash('sha256',$user_email),ENT_QUOTES,'UTF-8'); ?>" data-user-role="<?php echo htmlspecialchars($authUser['role'],ENT_QUOTES,'UTF-8'); ?>"><div class="container"><aside class="sidebar prism-sidebar">
<?php $prismCurrentPage = 'reports.php'; require __DIR__ . '/includes/prism-navigation.php'; ?>
<div class="sidebar-bottom"><div class="profile-dropdown-wrapper"><div class="sidebar-profile" id="profileToggle"><img src="<?php echo htmlspecialchars($profile_img,ENT_QUOTES,'UTF-8'); ?>" alt="Profile picture"><div class="profile-info"><h4><?php echo htmlspecialchars($user_name,ENT_QUOTES,'UTF-8'); ?></h4><p><?php echo htmlspecialchars($user_role,ENT_QUOTES,'UTF-8'); ?></p></div><i class="fa-solid fa-chevron-down dropdown-arrow"></i></div><div class="profile-menu" id="profileMenu"><a href="account.php#profile"><i class="fa-solid fa-user-gear"></i> Profile</a><a href="account.php#security"><i class="fa-solid fa-gear"></i> Settings</a><a href="account.php#activity"><i class="fa-solid fa-sliders"></i> Activity Logs</a><hr><a href="logout.php" class="logout-btn"><i class="fa-solid fa-right-from-bracket"></i> Log Out</a></div></div></div></aside>
<main class="main-content reports-page"><header class="topbar"><div class="reports-heading"><h1>Reports</h1><p>Generate and manage aggregate and student IERB progress reports.</p></div><div class="top-controls"><div class="theme-toggle" id="themeToggle"><i class="fa-solid fa-sun light-icon"></i><i class="fa-solid fa-moon dark-icon"></i></div></div></header>
<section class="report-tools"><button class="report-tool" id="generateSummarizedReport"><span class="report-tool-icon"><i class="fa-solid fa-file-lines"></i></span><span><strong>Generate Summarized Report</strong><small>One click — concise AI overview of all students</small></span><i class="fa-solid fa-bolt"></i></button><button class="report-tool" id="generateFullReport"><span class="report-tool-icon"><i class="fa-solid fa-file-contract"></i></span><span><strong>Generate Full Report</strong><small>One click — AI analysis plus complete detail for all students</small></span><i class="fa-solid fa-bolt"></i></button><button class="report-tool" id="openStudentReport"><span class="report-tool-icon"><i class="fa-solid fa-user-graduate"></i></span><span><strong>Generate Student Report</strong><small>Individual IERB progress summary</small></span><i class="fa-solid fa-chevron-right"></i></button></section>
<p class="report-ai-note" id="reportAiNote"></p>
<section class="report-history"><div class="report-history-heading"><div><h2>Report History</h2><p id="reportCount">0 reports</p></div><button id="exportExcel"><i class="fa-solid fa-file-excel"></i> Export Excel CSV</button></div><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Report Name</th><th>Date Generated</th><th>Type</th><th>Actions</th></tr></thead><tbody id="reportTableBody"></tbody></table></div></section><?php require __DIR__ . '/includes/ceu_footer.php'; ?>
</main></div>
<div class="report-modal" id="studentModal"><div class="report-modal-dialog"><div class="report-modal-heading"><div><span>Individual report</span><h2>Student Progress Report</h2></div><button data-close="studentModal"><i class="fa-solid fa-xmark"></i></button></div><form id="studentReportForm"><label>Select student</label><select id="reportStudent" required></select><button class="generate-report-button"><i class="fa-solid fa-file-pdf"></i> Generate PDF</button></form></div></div>

<script src="<?php echo htmlspecialchars(asset_url('assets/js/prism-ui.js'), ENT_QUOTES, 'UTF-8'); ?>"></script><script src="<?php echo htmlspecialchars(asset_url('assets/js/reports.js'), ENT_QUOTES, 'UTF-8'); ?>"></script></body></html>
