-- Separate v9 migration; tools/schema-v8-manual.sql is intentionally untouched.
-- MariaDB 10.4+; run only after backup, isolated staging validation and a maintenance window.
-- Edit these TWO settings deliberately. Requires CREATE/ALTER ROUTINE in addition to schema DDL.
-- DDL commits implicitly: failure can leave additive changes, but never advances schema_version.
-- Retry the entire script after reviewing the failure. Do not disable FOREIGN_KEY_CHECKS.
DELIMITER $$
SET @PRISM_V9_EXPECT_DB = 'REPLACE_WITH_EXACT_DATABASE_NAME'$$
SET @PRISM_V9_BACKUP_AND_STAGING_VERIFIED = 0$$
DROP PROCEDURE IF EXISTS prism_apply_retention_v9$$
CREATE PROCEDURE prism_apply_retention_v9()
BEGIN
    DECLARE got_lock INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        IF got_lock=1 THEN DO RELEASE_LOCK('prism_migrate'); END IF;
        RESIGNAL;
    END;
    IF DATABASE() IS NULL OR DATABASE()<>@PRISM_V9_EXPECT_DB OR @PRISM_V9_BACKUP_AND_STAGING_VERIFIED<>1 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Explicit target database, backup and staging confirmation required';
    END IF;
    IF @@SESSION.foreign_key_checks<>1 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Foreign-key enforcement required';
    END IF;
    SELECT GET_LOCK('prism_migrate',30) INTO got_lock;
    IF got_lock<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Migration lock unavailable'; END IF;
    IF COALESCE((SELECT v FROM schema_meta WHERE k='schema_version'),'') NOT IN ('8','9') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Verified schema v8 or v9 prerequisite required';
    END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE()
        AND TABLE_NAME IN ('users','students','advisers','documents','ierb_history','password_resets','reports','ai_outputs','notifications','activity_logs','calendar_deadlines','calendar_deadline_recipients','calendar_deadline_groups','schema_meta','stage_labels') AND ENGINE='InnoDB')<>15 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Expected fifteen InnoDB application tables required';
    END IF;
    ALTER TABLE `students` ADD COLUMN IF NOT EXISTS `retention_hold` TINYINT(1) NOT NULL DEFAULT 0;
    ALTER TABLE `students` ADD COLUMN IF NOT EXISTS `retention_hold_at` DATETIME NULL;
    ALTER TABLE `students` ADD COLUMN IF NOT EXISTS `retention_hold_by` INT NULL;
    ALTER TABLE `students` ADD COLUMN IF NOT EXISTS `retention_hold_reason` VARCHAR(500) NULL;
    ALTER TABLE `students` ADD COLUMN IF NOT EXISTS `purge_postponed_at` DATETIME NULL;
    ALTER TABLE `students` ADD COLUMN IF NOT EXISTS `purge_postponed_reason` VARCHAR(255) NULL;
    ALTER TABLE `students` ADD COLUMN IF NOT EXISTS `restored_at` DATETIME NULL;
    ALTER TABLE `advisers` ADD COLUMN IF NOT EXISTS `archived_at` DATETIME NULL;
    ALTER TABLE `advisers` ADD COLUMN IF NOT EXISTS `retention_hold` TINYINT(1) NOT NULL DEFAULT 0;
    ALTER TABLE `advisers` ADD COLUMN IF NOT EXISTS `retention_hold_at` DATETIME NULL;
    ALTER TABLE `advisers` ADD COLUMN IF NOT EXISTS `retention_hold_by` INT NULL;
    ALTER TABLE `advisers` ADD COLUMN IF NOT EXISTS `retention_hold_reason` VARCHAR(500) NULL;
    ALTER TABLE `advisers` ADD COLUMN IF NOT EXISTS `purge_postponed_at` DATETIME NULL;
    ALTER TABLE `advisers` ADD COLUMN IF NOT EXISTS `purge_postponed_reason` VARCHAR(255) NULL;
    ALTER TABLE `advisers` ADD COLUMN IF NOT EXISTS `restored_at` DATETIME NULL;
    ALTER TABLE `reports` ADD COLUMN IF NOT EXISTS `owner_student_id` INT NULL;
    ALTER TABLE `ai_outputs` ADD COLUMN IF NOT EXISTS `owner_student_id` INT NULL;
    ALTER TABLE `ai_outputs` ADD COLUMN IF NOT EXISTS `owner_document_id` VARCHAR(40) NULL;
    ALTER TABLE `calendar_deadlines` ADD COLUMN IF NOT EXISTS `creator_name` VARCHAR(190) NULL;
    CREATE TABLE IF NOT EXISTS account_purge_jobs (
        id CHAR(32) PRIMARY KEY, account_type VARCHAR(20) NOT NULL, account_id INT NOT NULL,
        identifier VARCHAR(100) NOT NULL, actor_id INT NOT NULL, method VARCHAR(30) NOT NULL,
        status VARCHAR(30) NOT NULL DEFAULT 'files_pending', manifest_sha256 CHAR(64) NOT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at DATETIME NULL,
        INDEX purge_job_status (status,created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    ALTER TABLE `students` ADD INDEX IF NOT EXISTS `student_archive_lifecycle` (archived_at,retention_hold);
    ALTER TABLE `advisers` ADD INDEX IF NOT EXISTS `adviser_archive_lifecycle` (archived_at,retention_hold);
    ALTER TABLE `reports` ADD INDEX IF NOT EXISTS `report_owner_student` (owner_student_id);
    ALTER TABLE `reports` ADD INDEX IF NOT EXISTS `report_stored_file` (filename);
    ALTER TABLE `documents` ADD INDEX IF NOT EXISTS `document_stored_file` (stored_name);
    ALTER TABLE `documents` ADD INDEX IF NOT EXISTS `document_previous_version` (supersedes_id);
    ALTER TABLE `ai_outputs` ADD INDEX IF NOT EXISTS `ai_owner_student` (owner_student_id);
    ALTER TABLE `ai_outputs` ADD INDEX IF NOT EXISTS `ai_owner_document` (owner_document_id);
    ALTER TABLE `notifications` ADD INDEX IF NOT EXISTS `notification_recipient` (recipient_type,recipient_id);
    ALTER TABLE `activity_logs` ADD INDEX IF NOT EXISTS `lifecycle_entity` (entity_type,entity_id);
    ALTER TABLE `activity_logs` ADD INDEX IF NOT EXISTS `lifecycle_student` (student_id);
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='account_purge_jobs' AND COLUMN_NAME='id' AND COLUMN_TYPE='char(32)' AND IS_NULLABLE='NO')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible account_purge_jobs.id'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='account_purge_jobs' AND COLUMN_NAME='account_type' AND COLUMN_TYPE='varchar(20)' AND IS_NULLABLE='NO')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible account_purge_jobs.account_type'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='account_purge_jobs' AND COLUMN_NAME='account_id' AND COLUMN_TYPE='int(11)' AND IS_NULLABLE='NO')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible account_purge_jobs.account_id'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='account_purge_jobs' AND COLUMN_NAME='identifier' AND COLUMN_TYPE='varchar(100)' AND IS_NULLABLE='NO')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible account_purge_jobs.identifier'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='account_purge_jobs' AND COLUMN_NAME='actor_id' AND COLUMN_TYPE='int(11)' AND IS_NULLABLE='NO')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible account_purge_jobs.actor_id'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='account_purge_jobs' AND COLUMN_NAME='method' AND COLUMN_TYPE='varchar(30)' AND IS_NULLABLE='NO')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible account_purge_jobs.method'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='account_purge_jobs' AND COLUMN_NAME='status' AND COLUMN_TYPE='varchar(30)' AND IS_NULLABLE='NO')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible account_purge_jobs.status'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='account_purge_jobs' AND COLUMN_NAME='manifest_sha256' AND COLUMN_TYPE='char(64)' AND IS_NULLABLE='NO')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible account_purge_jobs.manifest_sha256'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='account_purge_jobs' AND COLUMN_NAME='created_at' AND COLUMN_TYPE='datetime' AND IS_NULLABLE='NO')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible account_purge_jobs.created_at'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='account_purge_jobs' AND COLUMN_NAME='completed_at' AND COLUMN_TYPE='datetime' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible account_purge_jobs.completed_at'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='advisers' AND COLUMN_NAME='archived_at' AND COLUMN_TYPE='datetime' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible advisers.archived_at'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='advisers' AND COLUMN_NAME='retention_hold' AND COLUMN_TYPE='tinyint(1)' AND IS_NULLABLE='NO' AND COLUMN_DEFAULT='0')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible advisers.retention_hold'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='advisers' AND COLUMN_NAME='retention_hold_at' AND COLUMN_TYPE='datetime' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible advisers.retention_hold_at'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='advisers' AND COLUMN_NAME='retention_hold_by' AND COLUMN_TYPE='int(11)' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible advisers.retention_hold_by'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='advisers' AND COLUMN_NAME='retention_hold_reason' AND COLUMN_TYPE='varchar(500)' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible advisers.retention_hold_reason'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='advisers' AND COLUMN_NAME='purge_postponed_at' AND COLUMN_TYPE='datetime' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible advisers.purge_postponed_at'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='advisers' AND COLUMN_NAME='purge_postponed_reason' AND COLUMN_TYPE='varchar(255)' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible advisers.purge_postponed_reason'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='advisers' AND COLUMN_NAME='restored_at' AND COLUMN_TYPE='datetime' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible advisers.restored_at'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='ai_outputs' AND COLUMN_NAME='owner_student_id' AND COLUMN_TYPE='int(11)' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible ai_outputs.owner_student_id'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='ai_outputs' AND COLUMN_NAME='owner_document_id' AND COLUMN_TYPE='varchar(40)' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible ai_outputs.owner_document_id'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='calendar_deadlines' AND COLUMN_NAME='creator_name' AND COLUMN_TYPE='varchar(190)' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible calendar_deadlines.creator_name'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='reports' AND COLUMN_NAME='owner_student_id' AND COLUMN_TYPE='int(11)' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible reports.owner_student_id'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='students' AND COLUMN_NAME='retention_hold' AND COLUMN_TYPE='tinyint(1)' AND IS_NULLABLE='NO' AND COLUMN_DEFAULT='0')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible students.retention_hold'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='students' AND COLUMN_NAME='retention_hold_at' AND COLUMN_TYPE='datetime' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible students.retention_hold_at'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='students' AND COLUMN_NAME='retention_hold_by' AND COLUMN_TYPE='int(11)' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible students.retention_hold_by'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='students' AND COLUMN_NAME='retention_hold_reason' AND COLUMN_TYPE='varchar(500)' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible students.retention_hold_reason'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='students' AND COLUMN_NAME='purge_postponed_at' AND COLUMN_TYPE='datetime' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible students.purge_postponed_at'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='students' AND COLUMN_NAME='purge_postponed_reason' AND COLUMN_TYPE='varchar(255)' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible students.purge_postponed_reason'; END IF;
    IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='students' AND COLUMN_NAME='restored_at' AND COLUMN_TYPE='datetime' AND IS_NULLABLE='YES')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible students.restored_at'; END IF;
    IF (SELECT ENGINE FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='account_purge_jobs')<>'InnoDB' OR (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='account_purge_jobs')<>10 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible purge journal'; END IF;
    IF COALESCE((SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='students' AND INDEX_NAME='student_archive_lifecycle' AND INDEX_TYPE='BTREE' AND NON_UNIQUE=1 AND SUB_PART IS NULL),'')<>'archived_at,retention_hold' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible index student_archive_lifecycle'; END IF;
    IF COALESCE((SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='advisers' AND INDEX_NAME='adviser_archive_lifecycle' AND INDEX_TYPE='BTREE' AND NON_UNIQUE=1 AND SUB_PART IS NULL),'')<>'archived_at,retention_hold' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible index adviser_archive_lifecycle'; END IF;
    IF COALESCE((SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='reports' AND INDEX_NAME='report_owner_student' AND INDEX_TYPE='BTREE' AND NON_UNIQUE=1 AND SUB_PART IS NULL),'')<>'owner_student_id' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible index report_owner_student'; END IF;
    IF COALESCE((SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='reports' AND INDEX_NAME='report_stored_file' AND INDEX_TYPE='BTREE' AND NON_UNIQUE=1 AND SUB_PART IS NULL),'')<>'filename' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible index report_stored_file'; END IF;
    IF COALESCE((SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='documents' AND INDEX_NAME='document_stored_file' AND INDEX_TYPE='BTREE' AND NON_UNIQUE=1 AND SUB_PART IS NULL),'')<>'stored_name' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible index document_stored_file'; END IF;
    IF COALESCE((SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='documents' AND INDEX_NAME='document_previous_version' AND INDEX_TYPE='BTREE' AND NON_UNIQUE=1 AND SUB_PART IS NULL),'')<>'supersedes_id' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible index document_previous_version'; END IF;
    IF COALESCE((SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='ai_outputs' AND INDEX_NAME='ai_owner_student' AND INDEX_TYPE='BTREE' AND NON_UNIQUE=1 AND SUB_PART IS NULL),'')<>'owner_student_id' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible index ai_owner_student'; END IF;
    IF COALESCE((SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='ai_outputs' AND INDEX_NAME='ai_owner_document' AND INDEX_TYPE='BTREE' AND NON_UNIQUE=1 AND SUB_PART IS NULL),'')<>'owner_document_id' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible index ai_owner_document'; END IF;
    IF COALESCE((SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='notifications' AND INDEX_NAME='notification_recipient' AND INDEX_TYPE='BTREE' AND NON_UNIQUE=1 AND SUB_PART IS NULL),'')<>'recipient_type,recipient_id' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible index notification_recipient'; END IF;
    IF COALESCE((SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='activity_logs' AND INDEX_NAME='lifecycle_entity' AND INDEX_TYPE='BTREE' AND NON_UNIQUE=1 AND SUB_PART IS NULL),'')<>'entity_type,entity_id' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible index lifecycle_entity'; END IF;
    IF COALESCE((SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='activity_logs' AND INDEX_NAME='lifecycle_student' AND INDEX_TYPE='BTREE' AND NON_UNIQUE=1 AND SUB_PART IS NULL),'')<>'student_id' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible index lifecycle_student'; END IF;
    IF COALESCE((SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='account_purge_jobs' AND INDEX_NAME='PRIMARY' AND INDEX_TYPE='BTREE' AND NON_UNIQUE=0 AND SUB_PART IS NULL),'')<>'id' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible index PRIMARY'; END IF;
    IF COALESCE((SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='account_purge_jobs' AND INDEX_NAME='purge_job_status' AND INDEX_TYPE='BTREE' AND NON_UNIQUE=1 AND SUB_PART IS NULL),'')<>'status,created_at' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Incompatible index purge_job_status'; END IF;
    UPDATE advisers SET archived_at=NOW() WHERE status='Inactive' AND archived_at IS NULL;
    UPDATE calendar_deadlines d JOIN users u ON u.id=d.creator_user_id SET d.creator_name=u.full_name WHERE d.creator_name IS NULL;
    REPLACE INTO schema_meta (k,v) VALUES ('schema_version','9');
    DO RELEASE_LOCK('prism_migrate');
END$$
CALL prism_apply_retention_v9()$$
DROP PROCEDURE prism_apply_retention_v9$$
DELIMITER ;
-- Keep purge disabled. Run the reviewed verifier against the complete v9 manifest next.
